language: node_js

jobs:
  include:
    - stage: commit
      node_js: lts/*
      cache: npm
      script:
        - commitlint-travis
    - stage: test
      node_js: lts/*
      cache: npm
      script: npm run test
    - stage: release
      node_js: lts/*
      cache: npm
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
